name: Check dependency usage

on:
  pull_request:
    paths:
      - 'pnpm-lock.yaml'

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}

jobs:
  check-dependency:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Use Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .nvmrc
      - name: Build
        run: |
          pnpm i --no-frozen-lockfile
      - name: Comment
        run: |
          read -a array <<< "${PR_TITLE}"
          if [ "${array[2]}" == "dependency" ]; then
            node bin/cdxgen.js --exclude test/\*\* -t js --deep
            echo "Output of \`pnpm why ${array[3]}\`:" > _tree.txt
            echo "\`\`\`" >> _tree.txt
            pnpm why ${array[3]} >> _tree.txt
            echo "\`\`\`" >> _tree.txt
            echo "Output of \`jq\` on components:" >> _tree.txt
            echo "\`\`\`" >> _tree.txt
            jq --arg dep "${array[3]}@" '.components[] | select(."bom-ref" | test($dep)) | { group, name, version, purl, licenses }' bom.json >> _tree.txt
            echo "\`\`\`" >> _tree.txt
            echo "Output of \`jq\` on dependencies:" >> _tree.txt
            echo "\`\`\`" >> _tree.txt
            jq --arg dep "${array[3]}@" '.dependencies[] | select(.ref | test($dep))' bom.json >> _tree.txt
            jq --arg dep "${array[3]}@" '.dependencies[] | select(.dependsOn | any(test($dep)))' bom.json >> _tree.txt
            echo "\`\`\`" >> _tree.txt
          fi
        env:
          FETCH_LICENSE: true
          PR_TITLE: ${{ github.event.pull_request.title }}
      - uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        if: hashFiles('_tree.txt')
        with:
          message-path: _tree.txt
